apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-kubernetes-zabbix-helm-chart-proxy
  namespace: zabbix-monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
